### ISSUE TITLE
How to guarantee no caching?

### ISSUE THREAD

**Issue by Judekeyser** [mtakeshi1/power-usage-comparisons#4]
It is clearly stated in the specification of the experiment, that **no caching** must be done.

However, the `product` table is never modified, which makes it easy for nearly all ORM used, to actually cache that table; and nothing would go against it in the test. Some ORM (like the one of Django) operate first in-memory and flush to the database only when required. For those, since there is no proper configuration of proxies, the application might think it's alone and the ORM might decide to very lazily push into database, resulting in an under usage of IO operations.

I think most ORM/Framework will biase the test. More over, it is unfair for application that can prove they do not cache, as they require much more IO than the others.

I suggest to either strengthen the rules for everyone, what ever the price it costs in terms of configuration/debugging/validation, either relax the rules for everyone and allow a cache.

**Comment by mtakeshi1** [comment]
I will check this for django, but the ones we have so far (java, ruby) only have transaction level caching so they don't survive across requests. The node and golang version query the database directly

**Comment by Judekeyser** [comment]
The Python version only makes use of cursor-level caching, so that sounds legit too. However, from what I remember of Django's ORM, the caching can be quite agressive (even in a single-threaded application, I sometimes got surprised by the cache not updating the database the way it was expected).

Do you have a reference for Java, that hibernate does not cache?

**Comment by mtakeshi1** [comment]
For hibernate, by default, it does no 2nd level cache (the cache above the session / transaction level cache). You have to configure a CacheManagerFactory or something like that

**Comment by Judekeyser** [comment]
FYI, a page about laziness behavior of Django ORM : https://www.mattduck.com/2021-01-django-orm-result-cache.html

Doing  .all() without storing in global should be enough. However, I've been checking out this code : https://github.com/mtakeshi1/power-usage-comparisons/blob/1e974a9f725ed597a915aafed4b077d27bcfa78b/python/django_rest/products/views.py

It feels to me that the variables are static and thus statically cache the `.all()` . To me, this is not correct and violates the no-cache requirement of the application (see documentation about `.all()` and `QuerySet`. @bruno-ortiz I think it should be modified, and a proper `get()` in the spirit of the `OrderEntry` should be made to prevent caching.

**Comment by Judekeyser** [comment]
Okay I think this is actually fine:

https://www.django-rest-framework.org/api-guide/generic-views/?q=as_view#generic-views

See in particular the specification:

```
queryset - The queryset that should be used for returning objects from this view. Typically, you must either set this attribute, or override the get_queryset() method. If you are overriding a view method, it is important that you call get_queryset() instead of accessing this property directly, as queryset will get evaluated once, and those results will be cached for all subsequent requests.
```

So I guess if the view is not updated, the method `as_view` will forcefully re-evaluate the queryset.
